// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BackWI.Model
{
    public partial class Animals
    {
        public Guid IdAnimal { get; set; }
        public int NumId { get; set; }
        public string NameAnimal { get; set; }
        public string ScientificName { get; set; }
        public int Dangerousness { get; set; }
        public Guid TypeAnimal { get; set; }
        public bool DangerOfExtinction { get; set; }
        public string Image { get; set; }

        public virtual AnimalTypes TypeAnimalNavigation { get; set; }
    }
}