// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BackWI.Model
{
    public partial class Photographs
    {
        public Guid IdAnimal { get; set; }
        public Guid IdUser { get; set; }
        public int NumId { get; set; }
        public byte[] Image { get; set; }
    }
}