// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BackWI.Model
{
    public partial class Users
    {
        public Guid IdUser { get; set; }
        public int NumId { get; set; }
        public string Nick { get; set; }
        public string Email { get; set; }
        public string Passwordd { get; set; }
        public string NameUser { get; set; }
        public string FirtsSurname { get; set; }
        public string SecondSurname { get; set; }
    }
}